# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{flexpay}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Chandler"]
  s.date = %q{2010-03-24}
  s.email = %q{chris@flatterline.com}
  s.files = [
    "lib/flexpay.rb",
     "lib/flexpay/api_module.rb",
     "lib/flexpay/cobranding_api/v2009_01_09.rb",
     "lib/flexpay/cobranding_api/v2009_01_09/pipelines.rb",
     "lib/flexpay/exceptions.rb",
     "lib/flexpay/fps_api/v2008_09_17.rb",
     "lib/flexpay/fps_api/v2008_09_17/pay.rb",
     "lib/flexpay/fps_api/v2008_09_17/verify_signature.rb",
     "lib/flexpay/request.rb",
     "lib/flexpay/simple_pay_api/v2009_04_17.rb",
     "lib/flexpay/simple_pay_api/v2009_04_17/subscription_button.rb",
     "lib/flexpay/util.rb"
  ]
  s.homepage = %q{http://github.com/cchandler/flexpay}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{An API for using the Amazon Flexible Payment Service (FPS).}
  s.test_files = [
    "spec/units/api_spec.rb",
     "spec/units/pay_spec.rb",
     "spec/units/recurring_pipeline_spec.rb",
     "spec/units/signature_spec.rb",
     "spec/units/subscription_button_spec.rb",
     "spec/units/verify_signature_spec.rb",
     "spec/integrations/integrations_helper.rb",
     "spec/spec_helper.rb",
     "spec/units/units_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hpricot>, [">= 0.8.1"])
      s.add_runtime_dependency(%q<rest-client>, [">= 1.4.2"])
    else
      s.add_dependency(%q<hpricot>, [">= 0.8.1"])
      s.add_dependency(%q<rest-client>, [">= 1.4.2"])
    end
  else
    s.add_dependency(%q<hpricot>, [">= 0.8.1"])
    s.add_dependency(%q<rest-client>, [">= 1.4.2"])
  end
end

